language: node_js
install:
- npm install newman
script:
- node_modules/.bin/newman run "tests/Newman Test.postman_collection.json" -e "tests/JSON API Env.postman_environment.json" -d "tests/DataDrivenInput.csv"
