version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - newman/newman-run:
          collection: tests/collection.json 
          environment: tests/environment.json 
          iteration-data: tests/inputData.csv 

workflows:
  example-workflow:
    jobs:
      - example-job
