version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  newman-collection-run:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: tests/collection.json 
          environment: tests/environment.json 
          iteration-data: tests/inputData.csv 

workflows:
  newman-workflow:
    jobs:
      - newman-collection-run
